/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2019-12-20 07:20:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.exam_005fevent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.CommonUtil;

public final class event_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

		String today = CommonUtil.getToday();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!--\r\n");
      out.write("\t******************************************** \r\n");
      out.write("\t\ttitle : track2 수련생 성명\t\r\n");
      out.write("\t******************************************** \r\n");
      out.write(" -->\t\r\n");
      out.write("\t<title>track2 김성용</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\">\t\r\n");
      out.write("\t<link href=\"/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"/css/layout.css\" rel=\"stylesheet\" >\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("<!--\r\n");
      out.write("\t******************************************** \r\n");
      out.write("\t\t성명 : track2 수련생 성명\t\r\n");
      out.write("\t******************************************** \r\n");
      out.write(" -->\t\r\n");
      out.write("\t\t<div class=\"leftmargin\">\r\n");
      out.write("\t\t\t<h1>성명 : track2_김성용</h1>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"write_wrap\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"board_list\">\r\n");
      out.write("\t\t\t\t<form name=\"list\">\r\n");
      out.write("\t\t\t\t<table class=\"board_table\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"12%\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Event 제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"th_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"t_title\"  class=\"input_100Per\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Event 기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"th_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"date\" value=\"Year-Month-Day\" min=\"");
      out.print(today);
      out.write("\" name=\"t_start_date\" class=\"input_100px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t~\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"date\" value=\"Year-Month-Day\" min=\"");
      out.print(today);
      out.write("\" name=\"t_end_date\" class=\"input_100px\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"th_left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"t_contents\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"w\" name=\"t_work\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"저장\" class=\"btn_ok\" onClick=\"write123();\">&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"다시쓰기\" class=\"btn_reset\" >&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t<input type=\"button\" value=\"목록\" class=\"btn_list\" onClick=\"javascript:history.back();\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write(" <script>\r\n");
      out.write("\tfunction write123(){\r\n");
      out.write("\t\tvar fm = document.list;\r\n");
      out.write("\t\t\tif(fm.t_title.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\t\tfm.t_title.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\tif(fm.t_start_date.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"시작날짜 입력하세요\");\r\n");
      out.write("\t\t\t\tfm.t_start_date.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(fm.t_end_date.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"종료날짜 입력하세요\");\r\n");
      out.write("\t\t\t\tfm.t_end_date.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(fm.t_end_date.value < fm.t_start_date.value){\r\n");
      out.write("\t\t\t\talert(\"종료날짜를 다시 확인해주세요\");\r\n");
      out.write("\t\t\t\tfm.t_colseDate.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\t\t\r\n");
      out.write("\t\t\tif(fm.t_contents.value==\"\"){\r\n");
      out.write("\t\t\t\talert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t\t\tfm.t_contents.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tfm.action =\"/examUpdate\";\r\n");
      out.write("\t\tfm.method =\"post\";\r\n");
      out.write("\t\tfm.submit();\r\n");
      out.write("\t}\r\n");
      out.write(" </script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
