/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2020-01-08 06:54:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.CommonUtil;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1578461698463L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1576563329365L));
    _jspx_dependants.put("/common/common_session_info.jsp", Long.valueOf(1573107591886L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');

	String sessionName =
						CommonUtil.checkNull((String)session.getAttribute("session_name"));
	String sessionId =
						CommonUtil.checkNull((String)session.getAttribute("session_id"));
	String sessionLevel = 
						CommonUtil.checkNull((String)session.getAttribute("session_level"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <meta name=\"Author\" content=\"구송이\">\r\n");
      out.write("  <meta name=\"Keywords\" content=\"문화재청 덕수궁, 반응형 홈페이지\">\r\n");
      out.write("  <meta name=\"Description\" content=\"응용sw개발자를 위한 반응형 홈페이지\">\r\n");
      out.write("  <title>旅go</title>\r\n");
      out.write("  <script src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <link href=\"/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!--<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>-->\r\n");
      out.write("  <link href=\"/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/css/layout.css\" rel=\"stylesheet\">\t\r\n");
      out.write("  <link href=\"/css/headyoutube.css\" rel=\"stylesheet\">\t\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- jquery언어 사용법\r\n");
      out.write("\t1. jquery.js 기반으로 프로그램을 작성하기 때문에 jquery.js 파일을 다운 또는 CDN 방식으로 링크 건다\r\n");
      out.write("\t2. $(function() {\r\n");
      out.write("\t실행문;\r\n");
      out.write("\t});\r\n");
      out.write("\t-->\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".gnb>.nav_1depth>li\").hover(function(){\r\n");
      out.write("\t\t\t\t//console.log(\"gnb>.nav_1depth>li\");\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(\".clearfix\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//var activeTab = $(this).find(\"a\").attr(\"href\"); \r\n");
      out.write("                //$(activeTab).fadeIn(); \r\n");
      out.write("                //return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).children(\".nav_2depth\").stop().slideDown(\"fast\");\r\n");
      out.write("\t\t\t\t}, function(){\r\n");
      out.write("\t\t\t\t\t$(\".gnb>.nav_1depth>li\").removeClass();\r\n");
      out.write("\t\t\t\t\t$(this).children(\".nav_2depth\").stop().slideUp(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").click(function(e){\r\n");
      out.write("\t\t\t\t\t//$(this).addClass(\"active\")\r\n");
      out.write("\t\t\t\t\t//var num = $(this).index();\r\n");
      out.write("\t\t\t\t\t//$(\".taball\").hide().eq(num).show();\r\n");
      out.write("\t\t\t\t//}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction check_wLogon(){\r\n");
      out.write("\t\t\tvar fm = document.work;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goJoin(){\r\n");
      out.write("\t\t\tvar fm = document.join;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tvar fm = document.logo;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction com(){\r\n");
      out.write("\t\t\tvar fm = document.com;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction comway(){\r\n");
      out.write("\t\t\tvar fm = document.comw;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction recPlace(){\r\n");
      out.write("\t\t\tvar fm = document.recp;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction recPlace2(){\r\n");
      out.write("\t\t\tvar fm = document.recr;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gofr(){\r\n");
      out.write("\t\t\tvar fm = document.gofr;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gont(){\r\n");
      out.write("\t\t\tvar fm = document.gont;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write(" <!-- 웹문서 만들기 기본 공식\r\n");
      out.write(" 1. 요소를 어떻게 묶을 것인가? 그룹만들기\r\n");
      out.write(" 2. 그룹안에 적절한 태그 사용\r\n");
      out.write(" 3. class 이름 붙이고 css 적용\r\n");
      out.write(" -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sr-only\">\r\n");
      out.write("\t\t<p><a href=\"#contents\">본문 바로가기</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"top_navigation\">\r\n");
      out.write("\t\t<header class=\"header\">\r\n");
      out.write("\t\t\t<form name=\"js-youtubeForm\">\r\n");
      out.write("\t\t\t<nav class=\"top_left\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"/Index\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"https://www.kakaocorp.com/service/KakaoTalk\">KakaoTalk</a></li>\r\n");
      out.write("\t\t\t\t\t<li class =\"youTubeLi\">YouTube</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Google</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<nav class=\"top_right\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t");
if(sessionId.equals("")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"javascript:check_wLogon()\">LOGIN</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:goJoin()\">JOIN</a></li>\r\n");
      out.write("\t\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"loginstatus\">Welcome to ");
      out.print(sessionName);
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"javascript:logout()\">LOGOUT</a></li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<form name =\"gont\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gont\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"join\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"goj\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"golo\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"work\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gol\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"com\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"goc\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"comw\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gocw\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"recp\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gorp\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"recr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gorr\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"gofr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gofr\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"gnb_group\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\">旅go</h1>\r\n");
      out.write("\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav_1depth\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:com()\">Company</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:com()\">Introduction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:comway()\">Map</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"business01.html\">Recommend</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:recPlace2()\">Restaurant Recommend</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:recPlace()\">Attraction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">Travel to Korea</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">Planning with company</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">Cancellation/Refund</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">Event</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">Event</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">Event List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"board01.html\">Board</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:gont()\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Traveling Review</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Traveling Question</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:gofr()\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"line\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<section id=\"main_visual\">\r\n");
      out.write("\t\t<form name =\"js-pic\">\r\n");
      out.write("\t\t<div class=\"visual_wrap\">\r\n");
      out.write("\t\t<div class=\"youtubeDiv\">\r\n");
      out.write("\t\t<object title=\"YouTube video player\" class=\"youtube-player\" type=\"text/html\"  width=\"100%\" height=\"500px\"  data=\"//www.youtube.com/embed/vtY7HHq_2vU?autoplay=1&loop=1&theme=light&fs=1\" allowFullScreen></object>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t<h2 class=\"sr-only\">메인 비쥬얼</h2>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<!-- <li><img src=\"images/bg.png\" alt=\"학생단체관람\" class=\"w100\"></li> -->\r\n");
      out.write("\t\t\t\t<li class=\"one\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"visual_inner\">\r\n");
      out.write("\t\t\t\t<p class=\"title\">CREATIVE <strong>DESIGN</strong></p> \r\n");
      out.write("\t\t\t\t<p class=\"txt\">Challenging Technology Development, <br/> Leading-Edge Enterprise</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<p> join(Completion),login(Completion),logout(Completion),companyintro(Ing)</p>\r\n");
      out.write("\t\r\n");
      out.write("\t<section class=\"main_content\">\r\n");
      out.write("\t\t<h2 class=\"sr-only\">주요서비스<h2>\r\n");
      out.write("\t\t<div class=\"main_left\">\r\n");
      out.write("\t\t\t<div class=\"box1\">\r\n");
      out.write("\t\t\t\t<div class=\"txt_relative\">\r\n");
      out.write("\t\t\t\t\t<h3>ONLINE SHOP</h3>\r\n");
      out.write("\t\t\t\t\t<p>메인 상품은 관리자 페이지에서 선택 가능합니다.</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btn-border\">READ MORE</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"img_transition\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"main_center\">\r\n");
      out.write("\t\t\t<div class=\"box3\">\r\n");
      out.write("\t\t\t\t<h3 class=\"sr-only\">알림마당</h3>\r\n");
      out.write("\t\t\t\t<nav>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#sam01\">샘플제품</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#sam02\">샘플제품</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sample01 clearfix active\" id=\"sam01\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sam\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"title\" href=\"\">100원</a>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"date\">2018-09-27</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text\">빅데이터처리, JAVA, JSP, PHP, DB를 이용한 웹사이트</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"sample02 clearfix\" id=\"sam02\">\r\n");
      out.write("\t\t\t\t\t<div class=\"sam\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"title\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"title\" href=\"\">300원</a>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"date\">2018-09-27</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"text\">빅데이터처리, JAVA, JSP, PHP, DB를 이용한 웹사이트</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">적을게 없어</a><span>2018-09-27</span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> <!-- box3 -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div> <!-- main_center -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main_right\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".gnb>.nav_1depth>li\").hover(function(){\r\n");
      out.write("\t\t\t\t//console.log(\"gnb>.nav_1depth>li\");\r\n");
      out.write("\t\t\t\t$(this).parent().addClass(\"active\");\r\n");
      out.write("\t\t\t\t$(\".taball\").hide();\r\n");
      out.write("\t\t\t\t$($(this).attr(\"href\")).show();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"right_quick\">\r\n");
      out.write("\t\t<button class=\"btn btn-open\" type=\"button\"></button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t<address class=\"address\">\r\n");
      out.write("\t\t\t<p class=\"title\">본사</p>\r\n");
      out.write("\t\t\t(우)12345 대전광역시 서구 관저로48<br>\r\n");
      out.write("\t\t\t전화번호 042) 123-4567 팩스 042) 123-4567\r\n");
      out.write("\t\t</address>\r\n");
      out.write("\t\t<p class=\"copyright\">COPYRIGHT &copy.VISION. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("<script src=\"/js/indexBg.js\"></script>\r\n");
      out.write("<script src=\"/js/headerYoutube.js\"></script>\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
