/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2019-12-17 09:51:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1576576108087L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <meta name=\"Author\" content=\"구송이\">\r\n");
      out.write("  <meta name=\"Keywords\" content=\"문화재청 덕수궁, 반응형 홈페이지\">\r\n");
      out.write("  <meta name=\"Description\" content=\"응용sw개발자를 위한 반응형 홈페이지\">\r\n");
      out.write("  <title>旅go</title>\r\n");
      out.write("  <script src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <link href=\"/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!--<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>-->\r\n");
      out.write("  <link href=\"/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/css/layout.css\" rel=\"stylesheet\">\t\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- jquery언어 사용법\r\n");
      out.write("\t1. jquery.js 기반으로 프로그램을 작성하기 때문에 jquery.js 파일을 다운 또는 CDN 방식으로 링크 건다\r\n");
      out.write("\t2. $(function() {\r\n");
      out.write("\t실행문;\r\n");
      out.write("\t});\r\n");
      out.write("\t-->\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".gnb>.nav_1depth>li\").hover(function(){\r\n");
      out.write("\t\t\t\t//console.log(\"gnb>.nav_1depth>li\");\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(\".clearfix\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//var activeTab = $(this).find(\"a\").attr(\"href\"); \r\n");
      out.write("                //$(activeTab).fadeIn(); \r\n");
      out.write("                //return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).children(\".nav_2depth\").stop().slideDown(\"fast\");\r\n");
      out.write("\t\t\t\t}, function(){\r\n");
      out.write("\t\t\t\t\t$(\".gnb>.nav_1depth>li\").removeClass();\r\n");
      out.write("\t\t\t\t\t$(this).children(\".nav_2depth\").stop().slideUp(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").click(function(e){\r\n");
      out.write("\t\t\t\t\t//$(this).addClass(\"active\")\r\n");
      out.write("\t\t\t\t\t//var num = $(this).index();\r\n");
      out.write("\t\t\t\t\t//$(\".taball\").hide().eq(num).show();\r\n");
      out.write("\t\t\t\t//}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write(" <!-- 웹문서 만들기 기본 공식\r\n");
      out.write(" 1. 요소를 어떻게 묶을 것인가? 그룹만들기\r\n");
      out.write(" 2. 그룹안에 적절한 태그 사용\r\n");
      out.write(" 3. class 이름 붙이고 css 적용\r\n");
      out.write(" -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\tfunction formSearch(){\r\n");
      out.write("\t\tvar fm = document.work;\r\n");
      out.write("\t\tfm.action =\"/membernubServlet\";\r\n");
      out.write("\t\tfm.method =\"post\";\r\n");
      out.write("\t\tfm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"sr-only\">\r\n");
      out.write("\t\t<p><a href=\"#contents\">본문 바로가기</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"top_navigation\">\r\n");
      out.write("\t\t<header class=\"header\">\r\n");
      out.write("\t\t\t<nav class=\"top_left\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"/indexForm\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">KakaoTalk</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Gogle</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"top_right\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"javascript:goLogin()\">LOGIN</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">JOIN</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t<form name =\"work\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" value=\"gols\" name=\"t_work\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"gnb_group\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\">旅go</h1>\r\n");
      out.write("\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav_1depth\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"company01.html\">회사</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"company01.html\">회사소개</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"company02.html\">찾아오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"business01.html\">오스스메</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"business01.html\">추천맛집</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"business02.html\">추천명소</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">여행계획</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">여행코스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">여행취소/환불</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">이벤트</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">이벤트내역</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"board01.html\">게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"board01.html\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"board02.html\">여행후기</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"board03.html\">여행질문</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"board04.html\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"line\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<div class=\"sub_title\">\r\n");
      out.write("\t\t<h2>관리자 로그인</h2>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"location\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"btn_home\"><a href=\"company01.html\"><i class=\"fa fa-home\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">유틸리티<i class=\"fa fa-plus btn_plus\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\">관리자 로그인<i class=\"fa fa-plus btn_plus\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"dropdown_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"gratomgs/html\">비전소개</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"bg_admin\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"grap\">\r\n");
      out.write("\t\t\t\t<form name=\"admin\" method=\"post\" action=\"admin.html\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend class=\"sr-only\">관리자로그인</legend>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label for=\"id\" class=\"sr-only\">아이디입력</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"id\" placeholder=\"아이디를 입력하세요\" id=\"id\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<label for=\"pw\" class=\"sr-only\">패스원드입력</label>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"pw\" placeholder=\"패스워드를 입력하세요\" id=\"pw\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" onClick=\"admin_check();\" class=\"btn_admin\">로그인</a>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction admin_check(){\r\n");
      out.write("\t\t\tif(admin.id.value==\"\"){\r\n");
      out.write("\t\t\t\talter(\"아이디입력\");\r\n");
      out.write("\t\t\t\tadmin.id.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(admin.pw.value==\"\"){\r\n");
      out.write("\t\t\t\talter(\"패스워드입력\");\r\n");
      out.write("\t\t\t\tadmin.pw.focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tadmin.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".location .dropdown>a\").on(\"click\",function(e){\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tif($(this).next().is(\":visible\")){\r\n");
      out.write("\t\t\t\t\t$(\".location .dropdown > a\").next().hide();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\".location .dropdown > a\").next().hide();\r\n");
      out.write("\t\t\t\t\t$(this).next().show();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<?php include \"footer.html\"; ?>\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
