/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2019-12-19 06:20:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.Member_DAO;

public final class check_005fid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String id = (String)request.getAttribute("t_id");
	String result = (String)request.getAttribute("t_result");

      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\r\n");
      out.write("\t\t<script src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<title>아이디 중복 검사</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("\t#contain {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twidth: 360px;\r\n");
      out.write("\t\tmargin: 20px 20px 20px 20px;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tborder: 1px solid #bcbcbc;\r\n");
      out.write("\t\tbackground-color:#F2F2F2;\r\n");
      out.write("\t}\r\n");
      out.write("\t#box1 {\r\n");
      out.write("\t\twidth:340px;\r\n");
      out.write("\t\theight:150px;\r\n");
      out.write("\t\tpadding: 10px;\r\n");
      out.write("\t\tborder: 1px solid #bcbcbc;\r\n");
      out.write("\t\tcolor: #333;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#t2 {\r\n");
      out.write("\t\twidth: 320px;\r\n");
      out.write("\t\tborder:0px solid #CAC9D2;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.t1{\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t\tfont-size:25px;\t\r\n");
      out.write("\t\tcolor:#67656f;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#t2 i {\r\n");
      out.write("\tfont-size:30px;\r\n");
      out.write("\tcolor:#FFFFFF;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#t2 #yes {\r\n");
      out.write("\t\tcolor:#FFFFFF;\r\n");
      out.write("\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#t2 #no {\r\n");
      out.write("\t\tcolor:#FFFFFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t#t2 #yes:hover {\r\n");
      out.write("\t\tcolor:#40FF00;\r\n");
      out.write("\t\tfont-size:50px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\t\r\n");
      out.write("\t#t2 #no:hover {\r\n");
      out.write("\t\tcolor:#FF0000;\r\n");
      out.write("\t\tfont-size:50px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("\tfunction confirm(){\r\n");
      out.write("\t\topener.document.admin.id_check_value.value =\"");
      out.print(id);
      out.write("\";\r\n");
      out.write("\t\t//opener==부모(열어준창) ,id_check_value =받아온값 ,value =?\r\n");
      out.write("\t\topener.document.admin.t_pw.focus();\r\n");
      out.write("\t\twindow.close();\r\n");
      out.write("\t}\r\n");
      out.write("\t function confirm_cancel(){\r\n");
      out.write("\t  \t opener.document.admin.id_check_value.value =\"\"; \r\n");
      out.write("\t\t opener.document.admin.t_id.focus();\r\n");
      out.write("\t\t window.close();\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"contain\">\r\n");
      out.write("\t\t<div id=\"box1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<TABLE id=\"t2\" >\r\n");

				// 중복 앙~ 되어있을때
				if(result.equals("0")){

      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<TR align=center >\r\n");
      out.write("\t\t\t\t\t<td height=\"90\"><p class=\"t1\">사용 가능한 아이디 입니다.</p></td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=center >\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:confirm()\"><i id =\"yes\" class=\"far fa-smile-wink\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:confirm_cancel()\"><i id =\"no\" class=\"fas fa-sad-tear\"></i></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");

				// 중복 되어있을때
				} else if(result.equals("1")){

      out.write("\t\r\n");
      out.write("\t\t\t\t<TR align=center >\r\n");
      out.write("\t\t\t\t\t<td height=\"90\"><p class=\"t1\">등록된 아이디 입니다.<br>다른 아이디를 사용하세요!</p></td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");
      out.write("\t\t\t\t<TR align=center >\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:confirm_cancel()\"><i  id =\"no\" class=\"fas fa-sad-tear\"></i></a>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</TR>\r\n");

				} 

      out.write("\t\r\n");
      out.write("\t\t\t</TABLE>\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
