/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2020-01-07 05:55:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.CommonUtil;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1578373986150L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1576563329365L));
    _jspx_dependants.put("/common/common_session_info.jsp", Long.valueOf(1573107591886L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');

	String sessionName =
						CommonUtil.checkNull((String)session.getAttribute("session_name"));
	String sessionId =
						CommonUtil.checkNull((String)session.getAttribute("session_id"));
	String sessionLevel = 
						CommonUtil.checkNull((String)session.getAttribute("session_level"));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("  <meta name=\"Author\" content=\"구송이\">\r\n");
      out.write("  <meta name=\"Keywords\" content=\"문화재청 덕수궁, 반응형 홈페이지\">\r\n");
      out.write("  <meta name=\"Description\" content=\"응용sw개발자를 위한 반응형 홈페이지\">\r\n");
      out.write("  <title>旅go</title>\r\n");
      out.write("  <script src=\"/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("  <link href=\"/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<!--<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>-->\r\n");
      out.write("  <link href=\"/css/common.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/css/layout.css\" rel=\"stylesheet\">\t\r\n");
      out.write(" \r\n");
      out.write(" \t<!-- jquery언어 사용법\r\n");
      out.write("\t1. jquery.js 기반으로 프로그램을 작성하기 때문에 jquery.js 파일을 다운 또는 CDN 방식으로 링크 건다\r\n");
      out.write("\t2. $(function() {\r\n");
      out.write("\t실행문;\r\n");
      out.write("\t});\r\n");
      out.write("\t-->\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\".gnb>.nav_1depth>li\").hover(function(){\r\n");
      out.write("\t\t\t\t//console.log(\"gnb>.nav_1depth>li\");\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t//$(\".clearfix\").hide();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//var activeTab = $(this).find(\"a\").attr(\"href\"); \r\n");
      out.write("                //$(activeTab).fadeIn(); \r\n");
      out.write("                //return false;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(this).children(\".nav_2depth\").stop().slideDown(\"fast\");\r\n");
      out.write("\t\t\t\t}, function(){\r\n");
      out.write("\t\t\t\t\t$(\".gnb>.nav_1depth>li\").removeClass();\r\n");
      out.write("\t\t\t\t\t$(this).children(\".nav_2depth\").stop().slideUp(\"fast\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t\t\t//$(\".main_center .box3 nav ul li\").click(function(e){\r\n");
      out.write("\t\t\t\t\t//$(this).addClass(\"active\")\r\n");
      out.write("\t\t\t\t\t//var num = $(this).index();\r\n");
      out.write("\t\t\t\t\t//$(\".taball\").hide().eq(num).show();\r\n");
      out.write("\t\t\t\t//}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction check_wLogon(){\r\n");
      out.write("\t\t\tvar fm = document.work;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goJoin(){\r\n");
      out.write("\t\t\tvar fm = document.join;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tvar fm = document.logo;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction com(){\r\n");
      out.write("\t\t\tvar fm = document.com;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction comway(){\r\n");
      out.write("\t\t\tvar fm = document.comw;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction recPlace(){\r\n");
      out.write("\t\t\tvar fm = document.recp;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction recPlace2(){\r\n");
      out.write("\t\t\tvar fm = document.recr;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gofr(){\r\n");
      out.write("\t\t\tvar fm = document.gofr;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction gont(){\r\n");
      out.write("\t\t\tvar fm = document.gont;\r\n");
      out.write("\t\t\tfm.action = \"/HubServlet\";\r\n");
      out.write("\t\t\tfm.method = \"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write(" <!-- 웹문서 만들기 기본 공식\r\n");
      out.write(" 1. 요소를 어떻게 묶을 것인가? 그룹만들기\r\n");
      out.write(" 2. 그룹안에 적절한 태그 사용\r\n");
      out.write(" 3. class 이름 붙이고 css 적용\r\n");
      out.write(" -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sr-only\">\r\n");
      out.write("\t\t<p><a href=\"#contents\">본문 바로가기</a></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"top_navigation\">\r\n");
      out.write("\t\t<header class=\"header\">\r\n");
      out.write("\t\t\t<nav class=\"top_left\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"/Index\">HOME</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">KakaoTalk</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Gogle</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"top_right\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t");
if(sessionId.equals("")){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"javascript:check_wLogon()\">LOGIN</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"javascript:goJoin()\">JOIN</a></li>\r\n");
      out.write("\t\t\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"loginstatus\">Welcome to ");
      out.print(sessionName);
      out.write("</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"first\"><a href=\"javascript:logout()\">LOGOUT</a></li>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\t\t<form name =\"gont\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gont\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"join\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"goj\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"golo\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"work\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gol\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"com\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"goc\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"comw\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gocw\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"recp\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gorp\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"recr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gorr\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form name =\"gofr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name =\"t_work\" value=\"gofr\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"gnb_group\">\r\n");
      out.write("\t\t\t\t<h1 class=\"logo\">旅go</h1>\r\n");
      out.write("\t\t\t\t<nav class=\"gnb\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav_1depth\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"javascript:com()\">Company</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:com()\">Introduction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:comway()\">Map</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"business01.html\">Recommend</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:recPlace2()\">Restaurant Recommend</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:recPlace()\">Attraction</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">Travel to Korea</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">Planning with company</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">Cancellation/Refund</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"product01.html\">Event</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product01.html\">Event</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"product02.html\">Event List</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"board01.html\">Board</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav_2depth\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:gont()\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Traveling Review</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Traveling Question</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:gofr()\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"line\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<div class=\"sub_title\">\r\n");
      out.write("\t\t<h2>회원가입</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"bg_admin\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"grap\">\r\n");
      out.write("\t\t\t\t<form name=\"admin\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<h5>아이디</h5>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_id\" placeholder=\"아이디를 입력하세요\" id=\"id\">\r\n");
      out.write("\t\t\t\t\t\t<input class= \"idcheck\" type = \"button\" onClick=\"check_id()\" value = \"중복검사\" id=\"checkIdB\">\r\n");
      out.write("\t\t\t\t\t\t<h5>비밀번호</h5>\r\n");
      out.write("\t\t\t\t\t\t<input type =\"hidden\" name =\"id_check_value\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"t_pw\" placeholder=\"패스워드를 입력하세요\" id=\"pw1\">\r\n");
      out.write("\t\t\t\t\t\t<h5>비밀번호확인</h5>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"t_pw2\" placeholder=\"패스워드확인\" id=\"pw2\">\r\n");
      out.write("\t\t\t\t\t\t<h5>이름</h5>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_name\" placeholder=\"이름을 입력해주세요\" id=\"name\">\r\n");
      out.write("\t\t\t\t\t\t<h5>닉네임</h5>\r\n");
      out.write("\t\t\t\t\t\t<input type =\"hidden\" name =\"t_nname2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_nname\" placeholder=\"별명을 입력해주세요\" id=\"nname\">\r\n");
      out.write("\t\t\t\t\t\t<input class= \"idcheck\" type = \"button\" onClick=\"check_nickName()\" value = \"확인\" id=\"checkIdB\">\r\n");
      out.write("\t\t\t\t\t\t<h5>주소</h5>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_adress\" placeholder=\"주소를입력해주세요\" id=\"adress\">\r\n");
      out.write("\t\t\t\t\t\t<p>폰번호</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_phone1\" placeholder=\"핸드폰번호1\" id=\"phone1\">\r\n");
      out.write("\t\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_phone2\" placeholder=\"핸드폰번호2\" id=\"phone2\">\r\n");
      out.write("\t\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_phone3\" placeholder=\"핸드폰번호3\" id=\"phone3\">\r\n");
      out.write("\t\t\t\t\t\t<p>이메일</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_email1\" class=\"email\" id =\"email1\">&#64;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"t_email2\" class=\"email\" id =\"email2\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id = \"emailtype\" name=\"t_emailtype\" class=\"email\" onchange=\"passme();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<p>성별</p>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"t_sex\" value=\"w\" id =\"sex\"> 여자\r\n");
      out.write("      \t\t\t\t\t<input type=\"radio\" name=\"t_sex\" value=\"m\" id =\"sex\"> 남자\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\" onClick=\"admin_check();\" class=\"btn_admin\" >sign up</a>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction check_id(){\r\n");
      out.write("\t\tvar fm =document.admin;\r\n");
      out.write("\t\tvar id = fm.t_id.value;\r\n");
      out.write("\t\tvar title =\"아이디중복검사\";\r\n");
      out.write("\t\tvar url =\"/memberIdCheck\";\r\n");
      out.write("\t\t\tif(id ==\"\"){\r\n");
      out.write("\t\t\t\talert(\"입력된 아이디가 없습니다\");\r\n");
      out.write("\t\t\t\tid.focus();\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\twindow.open(\"\",title,\"width=450, height=250\");\r\n");
      out.write("\t\t\t\t//첫번째\"\"연결할페이지,두번째 창이름,3번째 사이즈\r\n");
      out.write("\t\t\t\tfm.target=title;\r\n");
      out.write("\t\t\t\tfm.action=url;\r\n");
      out.write("\t\t\t\tfm.method=\"post\";\r\n");
      out.write("\t\t\t\tfm.submit();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\tfunction check_nickName(){\r\n");
      out.write("\t\tvar fm =document.admin;\r\n");
      out.write("\t\tvar nname =fm.t_nname.value;\r\n");
      out.write("\t\tvar title =\"아이디중복검사\";\r\n");
      out.write("\t\tvar url =\"/memberNicknamecheck\";\r\n");
      out.write("\t\tif(nname ==\"\"){\r\n");
      out.write("\t\t\talert(\"입력된 닉네임이 없습니다\");\r\n");
      out.write("\t\t\tnname.focus();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\twindow.open(\"\",title,\"width=450, height=250\");\r\n");
      out.write("\t\t\t//첫번째\"\"연결할페이지,두번째 창이름,3번째 사이즈\r\n");
      out.write("\t\t\tfm.target=title;\r\n");
      out.write("\t\t\tfm.action=url;\r\n");
      out.write("\t\t\tfm.method=\"post\";\r\n");
      out.write("\t\t\tfm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction passme(){\r\n");
      out.write("\t\tvar target = document.admin.t_emailtype.value;\r\n");
      out.write("\t      // 옵션 value 값\r\n");
      out.write("\t   \tvar e2 =  document.getElementById(\"email2\");\r\n");
      out.write("\t     e2.value =  target;\r\n");
      out.write("\t     //인풋상자로 자바스크립트 값 넘기기\r\n");
      out.write("\t     // document.getElementById(\"email2\"); >>>id값\r\n");
      out.write("\t     // var target = document.all.t_emailtype.value; >>>>>name값\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction admin_check() {\r\n");
      out.write("\t\tvar form = document.admin;\r\n");
      out.write("\t\tif(form.t_id.value==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_id.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.id_check_value.value==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디 중복체크 해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_id.value != form.id_check_value.value){\r\n");
      out.write("\t\t\talert(\"아이디 변경후 중복검사를 실시해주세요\");\r\n");
      out.write("\t\t\tform.t_id.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_id.value.length > 15){\r\n");
      out.write("\t\t\talert(\"아이디를 15자 이내로 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_pw.value==\"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_pw.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(form.t_pw.value.length >15){\r\n");
      out.write("\t\t\talert(\"비밀번호는 15자 이내로 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_pw.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_pw2.value==\"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 재입력해주세요\");\r\n");
      out.write("\t\t\tform.t_pw2.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(form.t_pw.value != form.t_pw2.value){\r\n");
      out.write("\t\t\talert(\"비밀번호가 같지않습니다\");\r\n");
      out.write("\t\t\tform.t_pw.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_name.value==\"\") {\r\n");
      out.write("\t\t\talert(\"이름을 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_name.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(form.t_name.value.length > 20){\r\n");
      out.write("\t\t\talert(\"이름은 20자 이내로 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_nname.value==\"\") {\r\n");
      out.write("\t\t\talert(\"별명을 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_name.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\tif(form.t_nname.value.length > 20){\r\n");
      out.write("\t\t\talert(\"별명은 20자 이내로 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_nname2.value==\"\"){\r\n");
      out.write("\t\t\talert(\"닉네잉 중복체크 해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_nname.value != form.t_nname2.value){\r\n");
      out.write("\t\t\talert(\"닉네임 변경후 중복검사를 실시해주세요\");\r\n");
      out.write("\t\t\tform.t_nname.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_adress.value==\"\") {\r\n");
      out.write("\t\t\talert(\"주소를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_adress.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone1.value==\"\") {\r\n");
      out.write("\t\t\talert(\"번호를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_phone1.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone1.value.length > 3){\r\n");
      out.write("\t\t\talert(\"연락처는 3자리이내로 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_phone1.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone2.value==\"\") {\r\n");
      out.write("\t\t\talert(\"번호를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_phone2.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone2.value.length > 4){\r\n");
      out.write("\t\t\tform.t_phone2.focus();\r\n");
      out.write("\t\t\talert(\"연락처는 4자리이내로 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone3.value==\"\") {\r\n");
      out.write("\t\t\talert(\"번호를 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_phone3.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(form.t_phone3.value.length > 4){\r\n");
      out.write("\t\t\tform.t_phone3.focus();\r\n");
      out.write("\t\t\talert(\"연락처는 4자리이내로 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tif(form.t_email1.value==\"\") {\r\n");
      out.write("\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\tform.t_email1.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\tif(form.t_email1.value.length > 15){\r\n");
      out.write("\t\talert(\"이메일 아이디는 15자 이내로 입력해주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(form.t_emailtype.value != \"\"){\r\n");
      out.write("\t\tdocument.all.t_email2.value = form.t_emailtype.value;\r\n");
      out.write("\t} else{\r\n");
      out.write("\t\tif(form.t_email2.value==\"\") {\r\n");
      out.write("\t\t\talert(\"이메일을 입력해주세요\");\r\n");
      out.write("\t\t\tform.t_email2.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tif(form.t_email2.value.length > 15){\r\n");
      out.write("\t\talert(\"이메일 은 15자 이내로 입력해주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(form.t_sex.value==\"\") {\r\n");
      out.write("\t\talert(\"성별을 선택해주세요\");\r\n");
      out.write("\t\tform.t_sex.focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\t}\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tform.action =\"/memberJoin\";\r\n");
      out.write("\t\tform.method =\"post\";\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("\t<div class=\"container clearfix\">\r\n");
      out.write("\t\t<address class=\"address\">\r\n");
      out.write("\t\t\t<p class=\"title\">본사</p>\r\n");
      out.write("\t\t\t(우)12345 대전광역시 서구 관저로48<br>\r\n");
      out.write("\t\t\t전화번호 042) 123-4567 팩스 042) 123-4567\r\n");
      out.write("\t\t</address>\r\n");
      out.write("\t\t<p class=\"copyright\">COPYRIGHT &copy.VISION. ALL RIGHTS RESERVED.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
